author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
executables:
  purty:
    cc-options:
      - -static
    dependencies:
      - base == 4.12.0.0
      - purty
    ghc-options:
      - -O2
      - -rtsopts
      - -static
      - -threaded
      - -with-rtsopts=-N
    ld-options:
      - -pthread
    main: Main.hs
    source-dirs: src
    when:
      - condition: '!os(darwin)'
        ld-options:
          - -static
extra-source-files:
  - README.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-methods
  - -Wredundant-constraints
homepage: https://github.com/joneshf/purty#readme
library:
  dependencies:
    - base == 4.12.0.0
    - bytestring == 0.10.8.2
    - componentm == 0.0.0.2
    - optparse-applicative == 0.14.3.0
    - pathwalk == 0.3.1.2
    - purescript-cst == 0.13.6
    - rio == 0.1.14.0
    - text == 1.2.3.1
  source-dirs: lib
license: BSD3
maintainer: jones3.hardy@gmail.com
name: purty
tests:
  golden:
    dependencies:
      - base == 4.12.0.0
      - bytestring == 0.10.8.2
      - componentm == 0.0.0.2
      - purty
      - rio == 0.1.14.0
      - tasty == 1.2
      - tasty-golden == 2.3.2
      - tasty-hunit == 0.10.0.1
      - text == 1.2.3.1
    main: Main.hs
    source-dirs: test/golden
version: 5.0.0
